#Written by CorePropertiesLocator
#Fri May 21 14:28:38 UTC 2021
name=userOrg
config=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f//userOrg/solrconfig.xml
schema=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f//userOrg/schema.xml
dataDir=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f/data/userOrg
#dataDir=data
