#Written by CorePropertiesLocator
#Fri May 21 14:28:38 UTC 2021
name=deploymentConfiguration
config=/data/d38af4a3-c236-487d-94da-f80b6944c2be/eee4820e-6eb8-451f-9e5e-21f9ac46bede/deploymentConfiguration/solrconfig.xml
schema=/data/d38af4a3-c236-487d-94da-f80b6944c2be/eee4820e-6eb8-451f-9e5e-21f9ac46bede/deploymentConfiguration/schema.xml
dataDir=/data/d38af4a3-c236-487d-94da-f80b6944c2be/data/deploymentConfiguration
#dataDir=data
