apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bb88b8bf-63b3-452e-ad73-c3b849f54995
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  accessModes:
    - ReadWriteOnce # Must match the access mode of the PV
  resources:
    requests:
      storage: 5Gi # Requesting 5Gi of storage
