apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d38af4a3-c236-487d-94da-f80b6944c2be
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  accessModes:
    - ReadWriteOnce # Must match the access mode of the PV
  resources:
    requests:
      storage: 5Gi # Requesting 5Gi of storage
