apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baaa5a57-1f2e-48bd-95a4-9103c847a98a
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  accessModes:
    - ReadWriteOnce # Must match the access mode of the PV
  resources:
    requests:
      storage: 5Gi # Requesting 5Gi of storage
