apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-ingress-745c261a-c29a-41c1-a58d-dc4c35072b19
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-745c261a-c29a-41c1-a58d-dc4c35072b19
spec:
  ingressClassName: nginx
  rules:
    - host: park-6agq17.evt2qw.us-east-2.febe.kbs
      http:
        paths:
          - path: /solr/
            pathType: Prefix
            backend:
              service:
                name: solr-service-745c261a-c29a-41c1-a58d-dc4c35072b19
                port:
                  number: 80
