apiVersion: v1
kind: Service
metadata:
  name: solr-service-85be27a5-b73c-484a-909c-aacc2c914ce4
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-85be27a5-b73c-484a-909c-aacc2c914ce4
spec:
  selector:
    app: solr-85be27a5-b73c-484a-909c-aacc2c914ce4
  ports:
    - port: 80
      targetPort: 8983
      protocol: TCP
  type: ClusterIP
