apiVersion: v1
kind: PersistentVolume
metadata:
  name: 8d5d2c0f-5447-4ad5-889b-75e5d7a3a35f
spec:
  capacity:
    storage: 5Gi # The size of the volume
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  hostPath:
    path: "/Users/ravi.dhyani/Desktop/mine/git/pvc" # This is the path on the host node