apiVersion: v1
kind: PersistentVolume
metadata:
  name: 9e747131-cfc7-4b99-bf38-6fccfc36af88
spec:
  capacity:
    storage: 5Gi # The size of the volume
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  hostPath:
    path: "/Users/ravi.dhyani/Desktop/mine/git/pvc" # This is the path on the host node