apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr-deployment-c200e174-f5a6-44d3-8344-c4df610b9d8c
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-c200e174-f5a6-44d3-8344-c4df610b9d8c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr-c200e174-f5a6-44d3-8344-c4df610b9d8c
  template:
    metadata:
      labels:
        app: solr-c200e174-f5a6-44d3-8344-c4df610b9d8c
    spec:
      initContainers:
        - name: fix-permissions
          image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769-f5e66296-a68f-4fae-ab34-616938e14a6b-bc5fa525-1f32-4c53-bf17-b98dd59ff12e-9e747131-cfc7-4b99-bf38-6fccfc36af88:1.0.0
          command: 
            - sh
            - '-c'
            - |
              echo "Copying initial Solr data from image to PVC..."
              mkdir -p /data/9e747131-cfc7-4b99-bf38-6fccfc36af88/c200e174-f5a6-44d3-8344-c4df610b9d8c /data/9e747131-cfc7-4b99-bf38-6fccfc36af88/data
              cp -R /var/solr/data/* /data/9e747131-cfc7-4b99-bf38-6fccfc36af88/c200e174-f5a6-44d3-8344-c4df610b9d8c || true
              cp -R /var/solr/move/* /data/9e747131-cfc7-4b99-bf38-6fccfc36af88/data || true
              chown -R 8983:8983 /data
              chmod -R 777 /data
              echo "Done copying Solr cores."
          volumeMounts:
            - name: solr-data-volume
              mountPath: /data
          securityContext:
            runAsUser: 0 # Run as root to change ownership

      containers:
        - name: solr-c200e174-f5a6-44d3-8344-c4df610b9d8c
          image: ravi8881/2e49f282-85d5-4866-af7d-8133a75e6769-f5e66296-a68f-4fae-ab34-616938e14a6b-bc5fa525-1f32-4c53-bf17-b98dd59ff12e-9e747131-cfc7-4b99-bf38-6fccfc36af88:1.0.0
          ports:
            - containerPort: 8983
          env:
            - name: SOLR_OPTS
              value: "-Dsolr.allowPaths=/data"  
          volumeMounts:
            - name: solr-data-volume
              mountPath: /data # This path is where Solr looks for its cores
      volumes:
        - name: solr-data-volume
          persistentVolumeClaim:
            claimName: 9e747131-cfc7-4b99-bf38-6fccfc36af88 # This name must match the PVC metadata.name
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983