apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-ingress-306bbf55-4579-44a3-8c31-d7b296a25bc9
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-306bbf55-4579-44a3-8c31-d7b296a25bc9
spec:
  ingressClassName: nginx
  rules:
    - host: randr-bt8713.s8vq4a.us-east-2.febe.kbs
      http:
        paths:
          - path: /solr/
            pathType: Prefix
            backend:
              service:
                name: solr-service-306bbf55-4579-44a3-8c31-d7b296a25bc9
                port:
                  number: 80
