#Written by CorePropertiesLocator
#Fri May 21 14:28:38 UTC 2021
name=campaignSubmissions
config=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f/4bd7ef21-deca-430e-81c4-f8ae3f003bb6/campaignSubmissions/solrconfig.xml
schema=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f/4bd7ef21-deca-430e-81c4-f8ae3f003bb6/campaignSubmissions/schema.xml
dataDir=/data/9dd0c8bf-0a27-4293-9442-db5b86a7c07f/data/campaignSubmissions
#dataDir=data
