apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d9ae9c25-4bc5-4507-83f9-edf988812194
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  accessModes:
    - ReadWriteOnce # Must match the access mode of the PV
  resources:
    requests:
      storage: 5Gi # Requesting 5Gi of storage
