apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-ingress-8af58bbd-44fa-43a8-9b68-bba66385d4eb
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-8af58bbd-44fa-43a8-9b68-bba66385d4eb
spec:
  ingressClassName: nginx
  rules:
    - host: tms-71iayx.7xebgg.us-east-2.febe.kbs
      http:
        paths:
          - path: /solr/
            pathType: Prefix
            backend:
              service:
                name: solr-service-8af58bbd-44fa-43a8-9b68-bba66385d4eb
                port:
                  number: 80
