apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-ingress-bd1780bb-5416-460f-b58c-9c42d80d977b
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-bd1780bb-5416-460f-b58c-9c42d80d977b
spec:
  ingressClassName: nginx
  rules:
    - host: tms-9zaknu.q4ou7q.us-east-2.febe.kbs
      http:
        paths:
          - path: /solr/
            pathType: Prefix
            backend:
              service:
                name: solr-service-bd1780bb-5416-460f-b58c-9c42d80d977b
                port:
                  number: 80
