apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solr-ingress-874ca13c-c524-4ccf-b19a-dc3a040c1a68
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-874ca13c-c524-4ccf-b19a-dc3a040c1a68
spec:
  ingressClassName: nginx
  rules:
    - host: tms-o2axvq.ydozc8.us-east-2.febe.kbs
      http:
        paths:
          - path: /solr/
            pathType: Prefix
            backend:
              service:
                name: solr-service-874ca13c-c524-4ccf-b19a-dc3a040c1a68
                port:
                  number: 80
