apiVersion: v1
kind: Service
metadata:
  name: solr-service-8af58bbd-44fa-43a8-9b68-bba66385d4eb
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-8af58bbd-44fa-43a8-9b68-bba66385d4eb
spec:
  selector:
    app: solr-8af58bbd-44fa-43a8-9b68-bba66385d4eb
  ports:
    - port: 80
      targetPort: 8983
      protocol: TCP
  type: ClusterIP
