apiVersion: v1
kind: Service
metadata:
  name: solr-service-be6cbce0-496d-407a-93fe-b1dff24f9010
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
  labels:
    app: solr-be6cbce0-496d-407a-93fe-b1dff24f9010
spec:
  selector:
    app: solr-be6cbce0-496d-407a-93fe-b1dff24f9010
  ports:
    - port: 80
      targetPort: 8983
      protocol: TCP
  type: ClusterIP
