apiVersion: v1
kind: PersistentVolume
metadata:
  name: 9dd0c8bf-0a27-4293-9442-db5b86a7c07f
spec:
  capacity:
    storage: 5Gi # The size of the volume
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  hostPath:
    path: "/Users/ravi.dhyani/Desktop/mine/git/pvc" # This is the path on the host node